[package]
name = "kalaid"
version = "0.1.0"
authors = ["mungu42 <ajinkyaprabhu97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "0.6"
llvm-sys = "100"
regex = "*"
rustc-serialize = "0.3"


